name: cis537
channels:
  - conda-forge
dependencies:
  - conda-forge::flake8=3.5.0
  - conda-forge::ipykernel=4.8.2
  - conda-forge::ipywidgets=7.2.1
  - conda-forge::keras=2.2.2
  - conda-forge::nb_conda_kernels=2.1.1
  - conda-forge::notebook=5.6.0
  - conda-forge::numpy=1.14.5
  - conda-forge::pandas=0.23.3
  - conda-forge::python=3.6.6
  - conda-forge::requests=2.19.1
  - conda-forge::scikit-learn=0.19.2
  - conda-forge::scipy=1.1.0
  - conda-forge::tensorflow=1.10.0
  - conda-forge::theano=1.0.3
  - conda-forge::tqdm=4.23.4
